@host = https://localhost:7253

### Get all templates

GET {{host}}/api/templates
Accept: application/json


### Create template

POST {{host}}/api/templates
Content-Type: application/json

{
  "ownerUserId": "12311111-1111-1111-1111-111111111111",
  "name": "Haircut Booking",
  "slug": "haircut-booking",
  "description": "My first OpenBuildForm template"
}